spring:
  application:
    name: setzer
server:
  port: 8083

---

spring:
  config:
    activate:
      on-profile: test
  cloud:
    discovery:
      enabled: false
  r2dbc:
    url: r2dbc:h2:mem:///test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

---

spring:
  config:
    activate:
      on-profile: h2
  r2dbc:
    url: r2dbc:h2:mem:///test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
debug: true

---

spring:
  config:
    activate:
      on-profile: mysql
  r2dbc:
    url: r2dbc:mysql://localhost:3309/mm
    username: user
    password: password
