spring:
  application:
    name: setzer
server:
  port: 8083
logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG
---

spring:
  config:
    activate:
      on-profile: mysql
  r2dbc:
    url: r2dbc:mysql://localhost:3309/mm
    username: user
    password: password

---

spring:
  config:
    activate:
      on-profile: test
  r2dbc:
    url: r2dbc:h2:mem:///test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE


