spring:
  cloud:
    discovery:
      enabled: false
  r2dbc:
    url: r2dbc:pool:postgresql://account-service-db:5432/accounts
    username: postgres
    password: password
  flyway:
    url: jdbc:postgresql://account-service-db:5432/accounts
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    baseline-on-migrate: true
    locations: 'classpath:db/migration'

---

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8081/auth/realms/moneymaker

---

spring:
  rabbitmq:
    username: test
    password: test
    host: mm-mq
    port: 5672