spring:
  cloud:
    kubernetes:
      enabled: false
      discovery:
        enabled: false
    discovery:
      enabled: false
  r2dbc:
    url: r2dbc:h2:mem:///test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
