spring:
  cloud:
    discovery:
      enabled: true
  r2dbc:
    url: r2dbc:h2:mem:///~/db/testdb
    username: sa
    password:
  flyway:
    url: jdbc:h2:mem:~/db/testdb;DB_CLOSE_DELAY=-1
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    locations: 'classpath:db/migration,test_data'
server:
  port: 8083
ribbon:
  eureka:
    enabled: true

---

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/auth/realms/moneymaker

---

spring:
  rabbitmq:
    username: test
    password: test

---

logging:
  level:
    io.r2dbc: DEBUG