spring:
  cloud:
    discovery:
      enabled: true
  r2dbc:
    url: r2dbc:pool:postgresql://localhostb:5436/transactions
    username: postgres
    password: password
  flyway:
    url: jdbc:postgresql://localhostb:5436/transactions
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    baseline-on-migrate: true
    locations: 'classpath:db/migration'
server:
  port: 8090

---

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/auth/realms/moneymaker

---

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration