spring:
  cloud:
    discovery:
      enabled: true
  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/account
    username: keycloak
    password: password
  flyway:
    url: jdbc:mysql://localhost:3306/account
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
server:
  port: 8083

---

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/auth/realms/moneymaker

---

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration